name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Java LTS
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          tools-deps: latest

      - name: Check code
        run: clojure -Srepro -M:check
